# Generated by Django 5.2.7 on 2025-11-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MostViewNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MostViewNews_title', models.CharField(max_length=200)),
                ('MostViewNews_authorname', models.CharField(max_length=100)),
                ('MostViewNews_date', models.DateField()),
                ('MostViewNews_image', models.FileField(default=None, max_length=255, null=True, upload_to='mostviewnews')),
            ],
        ),
    ]
