# Generated by Django 5.2.7 on 2025-12-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostviewnews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostviewnews',
            name='category',
            field=models.CharField(blank=True, choices=[('Sports', 'Sports'), ('Magazine', 'Magazine'), ('Politics', 'Politics'), ('Technology', 'Technology'), ('Fashion', 'Fashion'), ('LifeStyle', 'LifeStyle')], max_length=30, null=True),
        ),
    ]
