# Generated by Django 5.2.7 on 2025-11-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LatestNews_title', models.CharField(max_length=200)),
                ('LatestNews_authorname', models.CharField(max_length=100)),
                ('LatestNews_date', models.DateField()),
                ('LatestNews_image', models.FileField(default=None, max_length=255, null=True, upload_to='latestnews')),
            ],
        ),
    ]
